const data = {
  players: [
    {
      id: 'p1',
      name: 'Deshaun Watson',
      team: 'Houston Texans',
      position: 'QB',
      seasonProjections: [
        {
          id: 'sp1',
          playerId: 'p1',
          season: 1,
          passingCompletions: 48,
          passingAttempts: 80,
          passingYards: 300,
          passingTds: 4,
          passingInts: 3,
          rushingAttempts: 20,
          rushingYards: 80,
          rushingTds: 4,
          receptions: 1,
          receivingYards: 8,
          receivingTds: 0,
        },
      ],
      seasonStats: [
        {
          id: 'ss1',
          season: 1,
          passingCompletions: 42,
          passingAttempts: 75,
          passingYards: 334,
          passingTds: 1,
          passingInts: 83,
          rushingAttempts: 2,
          rushingYards: 23,
          rushingTds: 2,
          receptions: 0,
          receivingYards: 0,
          receivingTds: 0,
          targets: 0,
          twoPointConversions: 3,
          fumbles: 0,
          otherTds: 0,
          playerId: 'p1',
        },
      ],
    },

    {
      id: 'p2',
      name: 'David Johnson',
      team: 'Arizona Cardinals',
      position: 'RB',
      seasonProjections: [
        {
          id: 'sp1',
          playerId: 'p1',
          season: 1,
          passingCompletions: 48,
          passingAttempts: 80,
          passingYards: 300,
          passingTds: 4,
          passingInts: 3,
          rushingAttempts: 20,
          rushingYards: 80,
          rushingTds: 4,
          receptions: 1,
          receivingYards: 8,
          receivingTds: 0,
        },
      ],
      seasonStats: [
        {
          id: 'ss1',
          season: 1,
          passingCompletions: 49,
          passingAttempts: 75,
          passingYards: 334,
          passingTds: 1,
          passingInts: 83,
          rushingAttempts: 2,
          rushingYards: 23,
          rushingTds: 2,
          receptions: 0,
          receivingYards: 0,
          receivingTds: 0,
          targets: 0,
          twoPointConversions: 3,
          fumbles: 0,
          otherTds: 0,
          playerId: 'p1',
        },
      ],
    },

    {
      id: 'p3',
      name: 'Larry Fitzgerald',
      team: 'Arizona Cardinals',
      position: 'WR',
      seasonProjections: [
        {
          id: 'sp1',
          playerId: 'p1',
          season: 1,
          passingCompletions: 48,
          passingAttempts: 80,
          passingYards: 300,
          passingTds: 4,
          passingInts: 3,
          rushingAttempts: 20,
          rushingYards: 80,
          rushingTds: 4,
          receptions: 1,
          receivingYards: 8,
          receivingTds: 0,
        },
      ],
      seasonStats: [
        {
          id: 'ss1',
          season: 1,
          passingCompletions: 49,
          passingAttempts: 75,
          passingYards: 334,
          passingTds: 1,
          passingInts: 83,
          rushingAttempts: 2,
          rushingYards: 23,
          rushingTds: 2,
          receptions: 0,
          receivingYards: 0,
          receivingTds: 0,
          targets: 0,
          twoPointConversions: 3,
          fumbles: 0,
          otherTds: 0,
          playerId: 'p1',
        },
      ],
    },
  ],
};

export default data;
